
<!-- this is brand html -->
<?php $model = Mage::getModel('brand/brand');?>
<?php $collection = $model->getCollection(); ?>
<?php $collection->addFieldToFilter('status',1);?>
<?php $collection->addOrder('sort_order','ASC');?>


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<style type="text/css">
    
</style>
<div style="display: flex;">
  <?php foreach ($collection as $brand): ?>
    <div class="card m-1" style="width: 12rem;">
      <a href="<?php echo $this->getRewriteUrl($brand) ?>">
        <img class="card-img-top" src="<?php echo Mage::getBaseUrl('media').$brand->image;?>" alt="Card image cap">
      </a>
    <div class="card-body">
      <h6 class="card-text"><?php echo $brand->name;?></h6>
    </div>
  </div>
  <?php endforeach ?>
</div>


